### ISSUE TITLE
Emulator home page iframe not showing in Microsoft Edge

### ISSUE THREAD

**Issue by davidhoness** [trinketapp/3D-testing#19] opened 2017-04-13 08:17 UTC
It seems the iframe isn't loading on Edge / Windows 10

Steps to reproduce

- Open Microsoft Edge
- Navigate to https://trinket.io/sense-hat
- Iframe doesn't load
  ![edge1](https://cloud.githubusercontent.com/assets/6640424/24996125/8f0bdfe4-2029-11e7-8c9d-75eb8a01c540.png)

I was using
Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393

**Comment by davidhoness** [comment] 2017-04-13 08:19
Works fine if you navigate directly to a trinket ID though.
![edge2](https://cloud.githubusercontent.com/assets/6640424/24996309/43fca6ea-202a-11e7-8753-c614c2396d14.png)

**Comment by ebertmi** [comment] 2017-04-13 08:49
I can reproduce this error on windows 10 with Creators Update installed. The console output indicates some problems with the landing page as it tries to load `scss` files which are not available and should not be requested at all. Maybe there is something broken in der grunt tasks?

![image](https://cloud.githubusercontent.com/assets/1634468/24997400/cfefd724-2036-11e7-817a-3696456c2c70.png)

**Comment by eah13** [comment] 2017-04-13 11:07
@waywaaard thanks for this. I wonder if these 404s are related to sourcemap handling.  If so, they might be unrelated - do they happen on other pages as well?  Anything in the console besides those 404s?  I'll have access to edge later today to investigate.

**Comment by brianpmarks** [comment] 2017-04-13 11:25
Since it's only happening on the sense-hat page and not in regular iframes, I suspect it has to do with how we load the code on that particular page (via the query string.) Looking into it now.

**Comment by eah13** [comment] 2017-04-14 12:45
@davidhoness the fix for this is in production.  Please re-test at your convenience.

Brian discovered that apparently Edge has decided to limit URL length, which required a different way of loading trinkets on the demo page.

**Comment by ebertmi** [comment] 2017-04-14 12:59
I still get those CSS 404 errors in Edge also by visiting this https://trinket.io/python/25f043a1a0 . However, the 2D version is loaded and displayed fine.

**Comment by eah13** [comment] 2017-04-20 14:11
Confirmed fixed

**Closed as completed by eah13** 2017-04-20 14:11 UTC
