### ISSUE TITLE
Rotation doesn't seem right

### ISSUE THREAD

**Issue by davidhoness** [trinketapp/3D-testing#12] opened 2017-04-10 14:01 UTC
It still seems like the pitch, roll and yaw angles are tied to world rotation as opposed to the model rotation.
Steps to reproduce an example:

Reset the model to the home position using the double-arrow button.
![1](https://cloud.githubusercontent.com/assets/6640424/24865099/254a49e2-1dfe-11e7-84f7-763674eefb14.png)
Not sure why this isn't 0, 0, 0? On Astro Pi mode it seems to be 0, 0, 180 too. I thought that was supposed to be 0, 0, 90.

Anyway, then move the USB ports to the top.
![2](https://cloud.githubusercontent.com/assets/6640424/24865173/661e086e-1dfe-11e7-8ce7-1c98d8e00661.png)

Now pitch the SD card slot up and the USB ports down. We're doing a pitch movement but the roll is what is changing.
![3](https://cloud.githubusercontent.com/assets/6640424/24865217/850a0016-1dfe-11e7-98d2-530cbb78e9d4.png)

**Comment by eah13** [comment] 2017-04-12 12:42
The math behind the values calculation is [here](https://github.com/trinketapp/traqball.js/blob/master/src/traqball.js#L287). I believe the correct trig at that point should fix this.

**Comment by eah13** [comment] 2017-04-14 14:04
The fix is deployed!

![screenshot 2017-04-14 at 10 01 34 am](https://cloud.githubusercontent.com/assets/1702745/25045273/72d2e766-20f9-11e7-8cce-44f21ff4d4f6.png)

[Rotated inverse matrix](https://github.com/trinketapp/traqball.js/blob/master/src/traqball.js#L282) was the answer.  *Obviously*.

Thanks a ton for the testing on this.  If there are any further problems please comment here and we'll investigate.

**Comment by davidhoness** [comment] 2017-04-18 08:53
I've had a look at the fix and that does seem to have done the trick. However, I noticed something else which is similar but to do with the feature you added to make it easier to turn the device around the yaw axis.

Steps to reproduce

- Rotate the device to be side on, looking directly at the HDMI port
  ![1](https://cloud.githubusercontent.com/assets/6640424/25122411/b3a55820-241c-11e7-92b9-498cda6e841b.png)
- Use yaw-drag feature
  ![2](https://cloud.githubusercontent.com/assets/6640424/25122422/c0570a14-241c-11e7-9a1d-bd2964b76f70.png)
- You're doing a pitch movement, but yaw is what is changing

I wonder if we should make the yaw-drag feature only available when at a particular orientation?

**Comment by eah13** [comment] 2017-04-18 12:22
@davidhoness thanks for this.  I'm able to replicate in the emulator following your instructions.

Have you compared with the physical device?  I can reproduce this there as well, so this may just be revealing the limitations of the Euler representation.

**Comment by davidhoness** [comment] 2017-04-19 13:07
Ah fascinating, so maybe it is right. I also see this with the physical hardware.

**Comment by eah13** [comment] 2017-04-20 14:14
Great!  Closing since this replicates physical device behavior

**Closed as completed by eah13** 2017-04-20 14:14 UTC
Labels: bug
